"""DRP- stage 3a, task 1: draw the pair set (§4) and write it for commit. Routes nothing.

§4, verbatim in effect: pools are lba-a6's measured nodes in each band, ascending node id, frame per
the shipped GraphStore. One random.Random(20260928). Strata drawn in the order DRP-T1, DRP-T2,
DRP-MID; each draw rng.sample(pool, 2) as (source, target); a repeated unordered pair is rejected
and redrawn. 40 pairs per stratum. Plus the replication companion (DRP-C8): graph-descriptives'
own FAMOUS draw, seed 20260927, regenerated by its script's rule.

Endpoint names may appear (§8 sealing); no interior is routed or named here.

    cd api && PYTHONIOENCODING=utf-8 uv run python -u \
      ../builder/analysis/2026-09-27-drp-stage3a/drp_pairs.py
"""
from __future__ import annotations

import random
import sys

sys.stdout.reconfigure(encoding="utf-8")
from drp_common import (A0_GRAPH, A0_SHA, DRP_SEED, HERE, N_PAIRS, STRATA, Map, draw,  # noqa: E402
                        replication_pairs, stratum_pool, write_json)

m = Map(A0_GRAPH, A0_SHA)
print(f"lba-a6: N {m.n:,}; measured {int(m.measured.sum()):,}; null {int((~m.measured).sum())}")

rng = random.Random(DRP_SEED)
out = {"seed": DRP_SEED, "graph_sha256": m.sha, "rule": "§4 of the DRP- pre-registration",
       "strata": {}}


def row(i, s, t):
    return {"i": i, "source": s, "target": t,
            "source_mbid": m.mbids[s], "target_mbid": m.mbids[t],
            "source_name": m.store.names[s], "target_name": m.store.names[t],
            "source_pctl": m.pl[s], "target_pctl": m.pl[t]}


for name, lo, hi, incl in STRATA:
    pool = stratum_pool(m, lo, hi, incl)
    pairs = draw(rng, pool)
    assert len(pairs) == N_PAIRS
    out["strata"][name] = {"band": [lo, hi, "closed" if incl else "half-open"],
                           "pool": len(pool),
                           "pairs": [row(i, s, t) for i, (s, t) in enumerate(pairs)]}
    print(f"{name}: pool {len(pool):,}; {len(pairs)} pairs drawn")

fam, _mid = replication_pairs(m)
out["strata"]["DRP-C8"] = {"band": "graph-descriptives FAMOUS (both >= 0.95), seed 20260927",
                           "pool": None,
                           "pairs": [row(i, s, t) for i, (s, t) in enumerate(fam)]}
print(f"DRP-C8: {len(fam)} pairs regenerated")

# Routability (§4): every endpoint an lba-a6 node, by construction; asserted anyway.
for st in out["strata"].values():
    for p in st["pairs"]:
        assert 0 <= p["source"] < m.n and 0 <= p["target"] < m.n and p["source"] != p["target"]

digest = write_json(HERE / "drp_pairs.json", out)
print(f"wrote drp_pairs.json sha256 {digest}")
