"""DRP-AM5 critique, probe: A0 only, shipped ApiConfig() defaults. Routes NO ceiling.

Questions served (DRP-Q10, DRP-Q11, DRP-Q12 of the brief):
  1. F_max(k) in float64, and whether any node's fame_lb_pctl sits exactly on a scheduled value.
  2. A0 victim_key ladders, presses 0..10, on graph-descriptives' own FAMOUS and MID draws
     (seed 20260927, regenerated by that script's rule). NOT the DRP draw (seed 20260928).
  3. b(s, t, X): the minimax bottleneck -- smallest possible highest-interior fame_lb_pctl over
     every s-t path with >= 1 interior, direct s-t edge forbidden, endpoints exempt, nodes in X
     removed, nulls at 0.0 (the shipped frame). Own heap search; never calls find_journey.
     Cross-checked at two points per pair by scipy BFS reachability (independent code):
     reachable at ceiling b, unreachable at the next-lower distinct percentile.
  4. DRP-G9(e) red control proxy: press-1 journeys with an interior > 0.99, and whether a 0.99
     ceiling with relaxation would be FORCED to diverge (b1 < m1, derived; no ceiling routed).
  5. DRP-C6 at depths 0..3 on A0; victims pressed at 0..3 above F_max(4); X_A0, H; R13 bounds.

    cd api && PYTHONIOENCODING=utf-8 UV_LINK_MODE=copy uv run python -u \
      ../builder/analysis/2026-09-27-drp-prereg-critique-2/drp_ceiling_probe.py
"""

from __future__ import annotations

import hashlib
import heapq
import json
import random
import struct
import sys
import time
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
A0 = Path("C:/dev/music-app/builder/scratch/graph-lba-a6.bin")
A0_SHA = "28311d81d264b8ee950d855aef4a812c93073263433d131c0ad1a982e5395d5b"
SEED_GD = 20260927
N_PAIRS = 40
MAX_K = 10
BAND = (7, 8, 9, 10)


def sha(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for c in iter(lambda: f.read(1 << 20), b""):
            h.update(c)
    return h.hexdigest()


got = sha(A0)
side = json.loads(A0.with_name(A0.name + ".json").read_text(encoding="utf-8"))["sha256"]
if not (got == side == A0_SHA):
    print(f"REFUSING: {got} / sidecar {side}", file=sys.stderr)
    sys.exit(2)
print(f"sha256 OK {A0.name} {got} (= sidecar)")

from artistpath_api import pathfinding as _pf  # noqa: E402
from artistpath_api.config import ApiConfig  # noqa: E402
from artistpath_api.graph_store import GraphStore  # noqa: E402
from artistpath_api.pathfinding import KNOWN, Exclusion, find_journey  # noqa: E402

_pf_file = Path(_pf.__file__).resolve()
assert (ROOT / "api/src").resolve() in _pf_file.parents, _pf_file
sys.path.insert(0, str(ROOT / "builder/analysis/2026-08-03-cap-reevaluation"))
from cre_ladder import victim_key  # noqa: E402
assert Path(sys.modules["artistpath_api.pathfinding"].__file__).resolve() == _pf_file
assert sys.modules["artistpath_api.pathfinding"].find_journey is find_journey
print(f"pathfinding: {_pf_file}")

import scipy.sparse as sp  # noqa: E402
from scipy.sparse.csgraph import breadth_first_order  # noqa: E402

payload = A0.read_bytes()
store = GraphStore.from_bytes(payload)
hdr = struct.Struct("<4sIIIQ")
_m, _v, n, e, ml = hdr.unpack_from(payload)
cur = hdr.size + (n + 1) * 4 + e * 4 + e * 4 + e
fame = json.loads(payload[cur: cur + ml])["fame_lb"]
measured = np.array([v is not None for v in fame], dtype=bool)
pctl = np.asarray(store.fame_lb_pctl, dtype=np.float64)
assert np.array_equal(pctl, GraphStore.fame_percentiles(fame))
print(f"N {n:,}  CSR entries {e:,}  measured {int(measured.sum()):,}  null {int((~measured).sum()):,}")
print(f"fame_lb_pctl dtype {store.fame_lb_pctl.dtype}; min {pctl.min()} max {pctl.max()}; "
      f"nodes > 1.0: {int((pctl > 1.0).sum())}; nodes == 1.0: {int((pctl == 1.0).sum())}")
distinct = np.unique(pctl)
print(f"distinct percentile values {distinct.size:,}; min positive gap "
      f"{np.diff(distinct).min():.3e}; median gap {np.median(np.diff(distinct)):.3e}")

# ------------------------------------------------------------------ 1. schedule arithmetic
print("\n## 1. F_max(k) in float64 (DRP-AM3 item 2)")


def f_max(k: int) -> float:
    return 1.0 if k <= 3 else max(0.0, 1.0 - 0.015 * (k - 3))


print("| k | repr(F_max) | nodes > F_max | nodes == F_max | lowest distinct pctl >= F_max | gap |")
print("|---|---|---|---|---|---|")
for k in range(0, 21):
    f = f_max(k)
    above = int((pctl > f).sum())
    eq = int((pctl == f).sum())
    i = int(np.searchsorted(distinct, f, side="left"))
    pstar = distinct[i] if i < distinct.size else float("nan")
    print(f"| {k} | {f!r} | {above:,} | {eq} | {pstar!r} | {pstar - f:.3e} |")
print(f"tabulated check: F_max(4,7,10,20) = {f_max(4)!r}, {f_max(7)!r}, {f_max(10)!r}, {f_max(20)!r}")
print(f"k at which F_max first reaches 0.0: {next(k for k in range(4, 200) if f_max(k) == 0.0)}")
print(f"slope to reach 0.70 at k=20: {(1 - 0.70) / 17:.5f} ({(1 - 0.70) / 17 / 0.015:.2f}x); "
      f"to 0.50: {(0.5) / 17:.5f} ({0.5 / 17 / 0.015:.2f}x); to 0.30: {0.7 / 17:.5f} "
      f"({0.7 / 17 / 0.015:.2f}x)")

# ------------------------------------------------------------------ 2. structure for the minimax
off = store.offsets.tolist()
nbr = store.neighbours.tolist()
pl = pctl.tolist()
ids = np.arange(n)
t1_nodes = ids[measured & (pctl >= 0.99)]
t2_nodes = ids[measured & (pctl >= 0.95) & (pctl < 0.99)]


def min_nbr(v: int) -> float:
    return min(pl[w] for w in nbr[off[v]:off[v + 1]])


print("\n## 2. Endpoint lower bound on any bottleneck: min neighbour fame_lb_pctl (nulls 0.0)")
for label, nodes in (("T1 (>= 0.99)", t1_nodes), ("T2 [0.95, 0.99)", t2_nodes)):
    lb = np.array([min_nbr(int(v)) for v in nodes])
    print(f"{label}: {nodes.size} nodes; min-neighbour pctl median {np.median(lb):.4f}; "
          f"share >= 0.90 (walled) {np.mean(lb >= 0.90):.4f}; > 0.91 {np.mean(lb > 0.91):.4f}; "
          f"> 0.925 {np.mean(lb > 0.925):.4f}; > 0.94 {np.mean(lb > 0.94):.4f}; "
          f"> 0.985 {np.mean(lb > 0.985):.4f}; > 0.99 {np.mean(lb > 0.99):.4f}")


def bottleneck(s: int, t: int, excl: set[int]) -> float:
    """Minimax over interiors; direct edge forbidden; endpoints exempt; inf if none."""
    excl = set(excl) - {s, t}
    best = {}
    pq = []
    for w in nbr[off[s]:off[s + 1]]:
        if w == t or w in excl:
            continue
        lw = pl[w]
        if lw < best.get(w, 2.0):
            best[w] = lw
            heapq.heappush(pq, (lw, w))
    done = set()
    while pq:
        lu, u = heapq.heappop(pq)
        if u in done:
            continue
        done.add(u)
        row = nbr[off[u]:off[u + 1]]
        for w in row:
            if w == t:
                return lu  # u != s by construction; first popped neighbour of t is optimal
        for w in row:
            if w == s or w in excl or w in done:
                continue
            lw = lu if lu >= pl[w] else pl[w]
            if lw < best.get(w, 2.0):
                best[w] = lw
                heapq.heappush(pq, (lw, w))
    return float("inf")


# scipy adjacency for the independent check
A = sp.csr_matrix((np.ones(e, dtype=np.int8), store.neighbours.astype(np.int64),
                   store.offsets.astype(np.int64)), shape=(n, n))


def reachable_under(s: int, t: int, c: float, excl: set[int]) -> bool:
    keep = pctl <= c
    keep[[s, t]] = True
    if excl:
        keep[list(excl - {s, t})] = False
    idx = np.flatnonzero(keep)
    pos = -np.ones(n, dtype=np.int64)
    pos[idx] = np.arange(idx.size)
    data = A.data.copy()
    for a, b in ((s, t), (t, s)):
        lo, hi = A.indptr[a], A.indptr[a + 1]
        data[lo:hi][A.indices[lo:hi] == b] = 0
    full = sp.csr_matrix((data, A.indices, A.indptr), shape=(n, n))
    full.eliminate_zeros()
    sub = full[idx][:, idx]
    order = breadth_first_order(sub, int(pos[s]), directed=False, return_predecessors=False)
    return bool(np.isin(pos[t], order))


def check_b(s: int, t: int, b: float, excl: set[int]) -> bool:
    if not np.isfinite(b):
        return not reachable_under(s, t, 1.0, excl)
    i = int(np.searchsorted(distinct, b, side="left"))
    assert distinct[i] == b, "bottleneck is not a node percentile"
    ok_at = reachable_under(s, t, b, excl)
    ok_below = (not reachable_under(s, t, distinct[i - 1], excl)) if i > 0 else True
    return ok_at and ok_below


# ------------------------------------------------------------------ 3. draws and A0 ladders
def draw(rng, pool):
    seen, out = set(), []
    while len(out) < N_PAIRS:
        s, t = rng.sample(pool, 2)
        k = frozenset((s, t))
        if k in seen:
            continue
        seen.add(k)
        out.append((s, t))
    return out


famous_pool = [int(i) for i in ids[measured & (pctl >= 0.95)]]
mid_pool = [int(i) for i in ids[measured & (pctl >= 0.30) & (pctl <= 0.70)]]
rng = random.Random(SEED_GD)
SETS = {"FAMOUS": draw(rng, famous_pool), "MID": draw(rng, mid_pool)}
print(f"\nseed {SEED_GD}; FAMOUS pool {len(famous_pool):,}; MID pool {len(mid_pool):,}")

cfg = ApiConfig()
print(f"ApiConfig() read at run time: w_known_ramp_fame_pctl {cfg.w_known_ramp_fame_pctl}, "
      f"floor_relax_known {cfg.floor_relax_known}")
key = victim_key(np.where(measured, pctl, np.nan), store.pop_raw, store.mbids)


def ladder(s, t):
    ex, out = [], []
    for k in range(MAX_K + 1):
        res = find_journey(store, s, t, ex, cfg)
        if res is None:
            out.append((None, "none", list(ex)))
            break
        path, rule = res
        out.append((path, rule, list(ex)))
        interior = path[1:-1]
        if not interior:
            break
        ex = ex + [Exclusion(node=min(interior, key=key), reason=KNOWN)]
    return out


def tier(s, t):
    a, b = pctl[s] >= 0.99, pctl[t] >= 0.99
    return "T1-like" if (a and b) else ("T2-like" if not (a or b) else "straddle")


GD_ROWS = {}
gd = (ROOT / "builder/analysis/2026-09-27-issue-200-graph-descriptives/"
      "graph_descriptives.out.txt").read_text(encoding="utf-8").splitlines()
sec = None
for line in gd:
    if line.startswith("### FAMOUS: per pair"):
        sec = "FAMOUS"
    elif line.startswith("### MID: per pair"):
        sec = "MID"
    elif line.startswith("###"):
        sec = None
    elif sec and line.startswith("| ") and not line.startswith("| #"):
        cells = [c.strip() for c in line.strip("|").split("|")]
        GD_ROWS.setdefault(sec, []).append(cells)

REC = {}
for name, pairs in SETS.items():
    t0 = time.time()
    REC[name] = []
    for i, (s, t) in enumerate(pairs):
        lad = ladder(s, t)
        b0 = bottleneck(s, t, set())
        REC[name].append({"s": s, "t": t, "lad": lad, "b0": b0,
                          "adj": t in nbr[off[s]:off[s + 1]], "tier": tier(s, t)})
        if (i + 1) % 10 == 0:
            print(f"  {name} {i + 1}/40  {time.time() - t0:.0f}s", flush=True)

# own-instrument check: d0/d5/d10 medians vs committed graph-descriptives rows (3 dp)
for name in SETS:
    match = 0
    for r, row in zip(REC[name], GD_ROWS[name]):
        mine = []
        for k in (0, 5, 10):
            if k < len(r["lad"]) and r["lad"][k][0] is not None:
                vals = [pctl[v] for v in r["lad"][k][0][1:-1] if measured[v]]
                mine.append(f"{np.median(vals):.3f}" if vals else "nan")
            else:
                mine.append("-")
        match += mine == [row[3], row[4], row[5]]
    print(f"own-ladder check vs graph_descriptives.out.txt d0/d5/d10 ({name}): {match} of 40 match")

# independent check of b0 at two points per pair
bad = 0
for name in SETS:
    for r in REC[name]:
        if not check_b(r["s"], r["t"], r["b0"], set()):
            bad += 1
print(f"b0 independent BFS check (reachable at b0, unreachable at next-lower): "
      f"{80 - bad} of 80 pass")


def mx(path):
    return max(pctl[v] for v in path[1:-1]) if path is not None and len(path) > 2 else None


# ------------------------------------------------------------------ 4. results
print("\n## 3. b0 (no user exclusions) distribution, A0")
for name in SETS:
    b = np.array([r["b0"] for r in REC[name]])
    fin = b[np.isfinite(b)]
    print(f"{name}: finite {fin.size}/40; min {fin.min():.4f} p10 {np.percentile(fin, 10):.4f} "
          f"median {np.median(fin):.4f} p90 {np.percentile(fin, 90):.4f} max {fin.max():.4f}; "
          f"> 0.99: {int((fin > 0.99).sum())}; > 0.985: {int((fin > 0.985).sum())}; "
          f"> 0.94: {int((fin > 0.94).sum())}; > 0.895: {int((fin > 0.895).sum())}; "
          f"== 0.0: {int((fin == 0.0).sum())}")
    if name == "FAMOUS":
        for tr in ("T1-like", "T2-like", "straddle"):
            bt = [r["b0"] for r in REC[name] if r["tier"] == tr]
            print(f"   {tr}: n {len(bt)}; b0 values " + ", ".join(f"{x:.4f}" for x in sorted(bt)))
    print(f"{name}: adjacent endpoint pairs {sum(r['adj'] for r in REC[name])}/40; stop rule by depth "
          + "; ".join(f"d{k}: " + ",".join(
              f"{u} {sum(1 for r in REC[name] if k < len(r['lad']) and r['lad'][k][1] == u)}"
              for u in ("natural", "forced", "adjacent_only", "none")) for k in (0, 1, 4, 7, 10)))

print("\n## 4. DRP-G9(e) red-control proxy: press 1 on A0 (FAMOUS draw), no ceiling routed")
cnt_gt, forced, rows = 0, 0, []
for r in REC["FAMOUS"]:
    if len(r["lad"]) < 2 or r["lad"][1][0] is None:
        rows.append("no press-1 journey")
        continue
    path1, _, ex1 = r["lad"][1]
    m1 = mx(path1)
    n_gt = sum(1 for v in path1[1:-1] if pctl[v] > 0.99)
    b1 = bottleneck(r["s"], r["t"], {x.node for x in ex1})
    assert check_b(r["s"], r["t"], b1, {x.node for x in ex1})
    cnt_gt += n_gt > 0
    # a 0.99 ceiling with DRP-AM2 relaxation sets c = max(0.99, b1); the A0 journey survives iff
    # its highest interior m1 <= c. b1 <= m1 always (the A0 journey is feasible).
    must_diverge = m1 is not None and m1 > max(0.99, b1)
    forced += must_diverge
    rows.append(f"{r['tier']}: m1 {m1:.4f} b1 {b1:.4f} interiors>0.99 {n_gt} diverge-forced {must_diverge}")
print(f"pairs whose A0 press-1 journey has an interior with fame_lb_pctl > 0.99: {cnt_gt} of 40")
print(f"pairs where a 0.99 ceiling (with relaxation) is forced to change the press-1 journey: "
      f"{forced} of 40")
for i, x in enumerate(rows, 1):
    print(f"  {i}: {x}")

print("\n## 5. DRP-C6 on A0 at depths 0-3: share of journeys with >= 1 interior at >= 0.99")
for name in SETS:
    for tr in (("all",) if name == "MID" else ("all", "T1-like", "T2-like", "straddle")):
        rs = [r for r in REC[name] if tr == "all" or r["tier"] == tr]
        parts = []
        for k in range(0, 4):
            js = [r["lad"][k][0] for r in rs if k < len(r["lad"]) and r["lad"][k][0] is not None]
            hit = sum(1 for p in js if any(pctl[v] >= 0.99 for v in p[1:-1]))
            parts.append(f"d{k} {hit}/{len(js)}")
        print(f"{name} {tr}: " + "; ".join(parts))

print("\n## 6. Victims pressed at presses 0-3 (identical in DRP-S0P3 by DRP-G9(e)) above F_max(4)=0.985")
tot, above = 0, 0
for r in REC["FAMOUS"]:
    if len(r["lad"]) > 4:
        vs = [x.node for x in r["lad"][4][2]]
        tot += len(vs)
        above += sum(1 for v in vs if pctl[v] > f_max(4))
print(f"FAMOUS: {above} of {tot} press-0..3 victims have fame_lb_pctl > 0.985, so at press 4 they "
      f"are in the user exclusions AND above the scheduled ceiling")

print("\n## 7. X_A0 (median over 7-10 of highest interior), H = X_A0 - b0, and DRP-R13 lower bounds")
for name in SETS:
    X, H, lbmed, pooled = [], [], [], []
    for r in REC[name]:
        mxs = [mx(r["lad"][k][0]) for k in BAND if k < len(r["lad"])]
        mxs = [x for x in mxs if x is not None]
        if len(mxs) < 4:
            continue
        x = float(np.median(mxs))
        X.append(x)
        H.append(x - r["b0"])
        lbs = [max(0.0, r["b0"] - f_max(k)) for k in BAND]
        lbmed.append(float(np.median(lbs)))
        pooled += lbs
    X, H, lbmed = map(np.array, (X, H, lbmed))
    print(f"{name}: band-readable {X.size}; X_A0 median {np.median(X):.4f}; H median {np.median(H):.4f} "
          f"min {H.min():.4f}; H < 0 (would violate the bound): {int((H < -1e-12).sum())}; "
          f"H >= 0.015: {int((H >= 0.015).sum())}")
    print(f"   r lower bound max(0, b0 - F_max(k)), k=7..10: per-pair median >= 0.05 on "
          f"{int((lbmed >= 0.05).sum())} of {lbmed.size} (median over pairs {np.median(lbmed):.4f}); "
          f"pooled (pair, depth) median {np.median(pooled):.4f}; share > 0 {np.mean(np.array(pooled) > 0):.3f}")
    if name == "FAMOUS":
        for tr in ("T1-like", "T2-like", "straddle"):
            sel = [float(np.median([max(0.0, r['b0'] - f_max(k)) for k in BAND]))
                   for r in REC[name] if r["tier"] == tr]
            print(f"   {tr}: per-pair median r lower bound: " + ", ".join(f"{x:.4f}" for x in sorted(sel)))

print("\n## 8. A0 per-depth payload (DRP-C2 form): median over pairs of interior n(d) / n(0)")
for name in SETS:
    parts = []
    for k in BAND:
        rat = [len(r["lad"][k][0]) - 2 for r in REC[name] if k < len(r["lad"]) and r["lad"][k][0]]
        rat = [ (len(r["lad"][k][0]) - 2) / (len(r["lad"][0][0]) - 2)
                for r in REC[name] if k < len(r["lad"]) and r["lad"][k][0] and len(r["lad"][0][0]) > 2]
        parts.append(f"d{k} {np.median(rat):.3f} (n {len(rat)}, distinct values {len(set(rat))})")
    print(f"{name}: " + "; ".join(parts))
print("\ndone")
