"""Render a practice-room day log into readable notes: each note verbatim, beside the journey it is about.

    python exploration/practice-room/notes_md.py 2026-09-29
    -> exploration/practice-room/logs/2026-09-29-notes.md

The notes are the owner's words, copied exactly. Nothing is summarised or interpreted here.
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from variants import VARIANTS  # noqa: E402

LABELS = {vid: label for vid, label, _f, _d in VARIANTS}
LABELS.update({"tiers_fast": "Fame ladder (faster)", "overlap_a": "Shared neighbours (deeper)",
               "shaped": "Shaped toll", "bold": "Fame toll (bold)"})


def main() -> None:
    day = sys.argv[1] if len(sys.argv) > 1 else ""
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", day):
        sys.exit("usage: notes_md.py YYYY-MM-DD")
    src = HERE / "logs" / f"{day}.jsonl"
    recs = [json.loads(line) for line in src.read_text(encoding="utf-8").splitlines() if line.strip()]
    notes = [r for r in recs if r["kind"] == "note"]
    shown = Counter((r["from"], r["to"]) for r in recs if r["kind"] == "journey")
    out = [f"# Practice-room notes, {day}", "",
           "**The owner's notes, verbatim**, each beside the journey on screen when it was saved. "
           f"Generated by `notes_md.py` from `logs/{day}.jsonl` (which also holds every journey shown, "
           "noted or not). Fame is the map's fame percentile (100 = most listened on ListenBrainz).", "",
           f"{len(notes)} notes; journeys shown per pair: "
           + "; ".join(f"{a} → {b} ({n})" for (a, b), n in shown.items()), ""]
    pair = None
    for r in notes:
        if (r["from"], r["to"]) != pair:
            pair = (r["from"], r["to"])
            out += [f"## {pair[0]} → {pair[1]}", ""]
        out.append(f"### {LABELS.get(r['column'], r['column'])}, press {r['press']}  ·  {r['at'][11:16]}")
        if r["dug_past"]:
            out.append(f"*Dug past:* {', '.join(r['dug_past'])}  ")
        if r["journey"]:
            out.append("*Journey:* " + " > ".join(f"{n} ({f:g})" for n, f in r["journey"]))
        out.append("")
        out += ["> " + line if line else ">" for line in r["note"].splitlines()]
        out.append("")
    dst = HERE / "logs" / f"{day}-notes.md"
    dst.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"wrote {dst.name}: {len(notes)} notes")


if __name__ == "__main__":
    main()
